sudo: false
dist: trusty
language: ruby
cache: bundler
rvm:
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - ruby-head

gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile

env:
  - DATABASE=sqlite
  - DATABASE=mysql
  - DATABASE=postgres

matrix:
  exclude:
    # DATABASE=sqlite doesn't work until rails 5.1
    - gemfile: gemfiles/rails_4.2.gemfile
      env: DATABASE=sqlite

    - gemfile: gemfiles/rails_5.0.gemfile
      env: DATABASE=sqlite
  allow_failures:
    # foreign keys not working right with mysql/pg and rails 4.2
    - gemfile: gemfiles/rails_4.2.gemfile
      env: DATABASE=mysql

    - gemfile: gemfiles/rails_4.2.gemfile
      env: DATABASE=postgres

addons:
  code_climate:
    repo_token: 30c89fe1988d654211e1d65cdb44f1dca0f89cea1bfe456ceb1ce67e6daf17b8

# regular test configuration
after_success:
  - bundle exec codeclimate-test-reporter

before_script:
  - psql -c 'CREATE DATABASE db_subsetter;' -U postgres
  - mysql -e 'CREATE DATABASE db_subsetter;'

services:
  - mysql
  - postgresql

script:
  - bundle exec rake test
  - bundle exec rake rubocop
branches:
  except:
    - windows
