version: 1.0.{build}-{branch}
image: Visual Studio 2017
cache:
  - vendor/bundle

services:
  - mssql2017

environment:
  matrix:
    - RUBY_VERSION: 24

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - bundle config --local path vendor/bundle
  - bundle install
  - docker version
  - docker pull ruby:2.4.2-stretch

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v
  - sqlcmd -S "(local)" -U "sa" -P "Password12!" -Q "CREATE DATABASE db_subsetter;" -d "master"

test_script:
  - bundle exec rake test DATABASE=mssql
